all: client6
client1:client1.cpp
	g++ -std=c++11 $^ -o $@
client2:client2.cpp
	g++ -std=c++11 $^ -o $@
client3:client3.cpp
	g++ -std=c++11 $^ -o $@
client4:client4.cpp
	g++ -std=c++11 $^ -o $@
client5:client5.cpp
	g++ -std=c++11 $^ -o $@
client6:client6.cpp
	g++ -std=c++11 $^ -o $@

.PHONY:clean
clean:
	@rm -rf client1 client2 client3 client4 client5 client6


